name: Python Package CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - "problems/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine toml # toml for version extraction, build for package building, twine for uploading

    - name: Get project version
      id: get_version
      run: |
        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        echo "project_version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build distribution packages
      run: python -m build

    - name: Publish package to PyPI
      if: success()
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        # If your username is not '__token__', you can specify it like this:
        # username: __token__
